assets:
  tempVolumeUid: 8cc02aed-a60e-473c-940f-b0003e752168 # Users
dateModified: 1644541443
email:
  fromEmail: jack@jacksutherland.com
  fromName: ARcollective
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0af355c3-8627-488e-a24f-ef9a3a86d4c4: ARcollective # ARcollective
    1c7bcf9a-6c39-4768-af29-49358336b6b8: Homepage # Homepage
    8cc02aed-a60e-473c-940f-b0003e752168: Users # Users
    26ab29ca-cb3b-41ab-b6f9-4c5900b48562: 'Coming Soon' # Coming Soon
    71bfb228-82c3-4116-9400-b6a0aae6c71d: Common # Common
    6390d754-bbd7-44f8-b465-d8bd2e08ce07: Homepage # Homepage
    a32f71af-8b81-464c-aac9-7253ef262b35: 'Public Schema' # Public Schema
    c98ac2b6-ea46-48bb-9d12-7e5979cb6df2: ARcollective # ARcollective
    e5944d3a-892c-4a5d-9594-2241d295c2eb: 'Coming Soon' # Coming Soon
    e34616c9-44d4-407e-8d19-8db2693209ae: Brand # Brand
system:
  edition: pro
  live: true
  name: ARcollective
  retryDuration: null
  schemaVersion: 3.7.32
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: ''
  photoSubpath: null
  photoVolumeUid: 8cc02aed-a60e-473c-940f-b0003e752168 # Users
  requireEmailVerification: true
  suspendByDefault: false
  validateOnPublicRegistration: false
