assets:
  tempVolumeUid: 8cc02aed-a60e-473c-940f-b0003e752168 # Users
dateModified: 1644539211
email:
  fromEmail: jack@jacksutherland.com
  fromName: ARcollective
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0af355c3-8627-488e-a24f-ef9a3a86d4c4: ARcollective # ARcollective
    8cc02aed-a60e-473c-940f-b0003e752168: Users # Users
    71bfb228-82c3-4116-9400-b6a0aae6c71d: Common # Common
    a32f71af-8b81-464c-aac9-7253ef262b35: 'Public Schema' # Public Schema
    c98ac2b6-ea46-48bb-9d12-7e5979cb6df2: ARcollective # ARcollective
    e34616c9-44d4-407e-8d19-8db2693209ae: Brand # Brand
system:
  edition: pro
  live: true
  name: ARcollective
  retryDuration: null
  schemaVersion: 3.7.32
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: ''
  photoSubpath: null
  photoVolumeUid: 8cc02aed-a60e-473c-940f-b0003e752168 # Users
  requireEmailVerification: true
  suspendByDefault: false
  validateOnPublicRegistration: false
